### ISSUE TITLE
GLIBC Version

### ISSUE THREAD

**Issue by cemalgnlts** [ANSH3LL/solar2d-appimage#1]
Hi,

I get this error when I try to run the AppImage file:

```
/tmp/.mount_Solar2CaLtn7/usr/local/bin/Solar2D/Solar2DSimulator: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_Solar2CaLtn7/usr/lib/libunistring.so.2)
/tmp/.mount_Solar2CaLtn7/usr/local/bin/Solar2D/Solar2DSimulator: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Solar2CaLtn7/usr/lib/libunistring.so.2)
```

I don't know what you are doing, but I wanted to ask if there is a way to solve it.

**Comment by ANSH3LL** [comment]
@cemalgnlts Could you please share which linux distro you're running? Also share the version info

**Comment by cemalgnlts** [comment]
Google Cloud Shell
```
Linux cs-123-default 6.1.58+ #1 SMP PREEMPT_DYNAMIC Mon Jan 29 15:19:25 UTC 2024 x86_64 GNU/Linux
```

When I did some research, I found that it has to do with the version of the `GLIBC` library. This is the version that Google Cloud Shell uses:
```
cloudshell:~$ ldd --version
ldd (Debian GLIBC 2.31-13+deb11u8) 2.31
```

I thought that maybe it could work with lower library support by downgrading a process you did, but of course it could also be Solar2D.

**Comment by ANSH3LL** [comment]
I didn't build the affected library myself and so can't rebuild it with support for an older GLIBC.

Maybe you could try setting up a cloud shell instance that contains a newer GLIBC.

You could also install Linux Mint in a virtual machine, since that's how I built the appimage.
